alias sl='ls'

cd ~

#export PS1="$ "
if test -n $WSLENV; then
   export PS1="${debian_chroot:+($debian_chroot)}\[\033[01;34m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\n\$ "
   export DISPLAY=localhost:0.0
else
   export PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;32m\]\w\[\033[00m\]\n\$ "
fi

export PATH=~/bin:$PATH

alias clip="xsel -b"
alias explorer="explorer.exe"

